"""
Prompts Package
Centralized prompt templates for all agents
"""

from .monitoring_prompts import (
    MONITORING_SYSTEM_PROMPT,
    ADHERENCE_ANALYSIS_PROMPT,
    PATTERN_ANALYSIS_PROMPT,
    SYMPTOM_ANALYSIS_PROMPT,
    SINGLE_SYMPTOM_ANALYSIS_PROMPT,
    COMMON_SIDE_EFFECTS
)

from .planning_prompts import (
    PLANNING_SYSTEM_PROMPT,
    SCHEDULE_OPTIMIZATION_PROMPT,
    REPLAN_SCHEDULE_PROMPT,
    INTERACTION_CHECK_PROMPT,
    SCHEDULE_QUERY_PROMPT,
    KNOWN_INTERACTIONS,
    FOOD_REQUIREMENTS
)

from .barrier_prompts import (
    BARRIER_SYSTEM_PROMPT,
    BARRIER_PRIORITIZATION_PROMPT,
    COST_ASSISTANCE_PROMPT,
    SIDE_EFFECT_ANALYSIS_PROMPT,
    FORGETFULNESS_STRATEGY_PROMPT,
    COMPLEXITY_SIMPLIFICATION_PROMPT,
    INTERVENTION_TEMPLATES
)

from .liaison_prompts import (
    LIAISON_SYSTEM_PROMPT,
    CLINICAL_NARRATIVE_PROMPT,
    ESCALATION_MESSAGE_PROMPT,
    CARE_COORDINATION_PROMPT,
    FHIR_CODING_SYSTEMS,
    ADHERENCE_LOINC_CODES,
    SEVERITY_SNOMED_CODES,
    REPORT_SECTIONS,
    ESCALATION_TIMEFRAMES
)

__all__ = [
    # Monitoring prompts
    "MONITORING_SYSTEM_PROMPT",
    "ADHERENCE_ANALYSIS_PROMPT",
    "PATTERN_ANALYSIS_PROMPT",
    "SYMPTOM_ANALYSIS_PROMPT",
    "SINGLE_SYMPTOM_ANALYSIS_PROMPT",
    "COMMON_SIDE_EFFECTS",
    
    # Planning prompts
    "PLANNING_SYSTEM_PROMPT",
    "SCHEDULE_OPTIMIZATION_PROMPT",
    "REPLAN_SCHEDULE_PROMPT",
    "INTERACTION_CHECK_PROMPT",
    "SCHEDULE_QUERY_PROMPT",
    "KNOWN_INTERACTIONS",
    "FOOD_REQUIREMENTS",
    
    # Barrier prompts
    "BARRIER_SYSTEM_PROMPT",
    "BARRIER_PRIORITIZATION_PROMPT",
    "COST_ASSISTANCE_PROMPT",
    "SIDE_EFFECT_ANALYSIS_PROMPT",
    "FORGETFULNESS_STRATEGY_PROMPT",
    "COMPLEXITY_SIMPLIFICATION_PROMPT",
    "INTERVENTION_TEMPLATES",
    
    # Liaison prompts
    "LIAISON_SYSTEM_PROMPT",
    "CLINICAL_NARRATIVE_PROMPT",
    "ESCALATION_MESSAGE_PROMPT",
    "CARE_COORDINATION_PROMPT",
    "FHIR_CODING_SYSTEMS",
    "ADHERENCE_LOINC_CODES",
    "SEVERITY_SNOMED_CODES",
    "REPORT_SECTIONS",
    "ESCALATION_TIMEFRAMES"
]
