"""
API Schemas Module
Pydantic models for request/response validation
"""

from api.schemas.patient import (
    PatientBase,
    PatientCreate,
    PatientUpdate,
    PatientPreferencesUpdate,
    ConditionAdd,
    AllergyAdd,
    PatientResponse,
    PatientSummary,
    PatientDetailResponse,
    PatientList,
    PatientSearch,
)

from api.schemas.medication import (
    MedicationBase,
    MedicationCreate,
    MedicationUpdate,
    MedicationDiscontinue,
    InteractionCheckRequest,
    MedicationSearch,
    MedicationResponse,
    MedicationSummary,
    MedicationDetail,
    MedicationList,
    DrugInteraction,
    InteractionCheckResponse,
    DrugSearchResult,
    SideEffectsResponse,
    FoodRequirementsResponse,
    RefillNeeded,
    RefillList,
)

from api.schemas.adherence import (
    AdherenceStatusEnum,
    AdherenceLogCreate,
    DoseTaken,
    DoseMissed,
    DoseSkipped,
    AdherenceQuery,
    AdherenceLogResponse,
    AdherenceLogDetail,
    AdherenceRate,
    AdherenceStreak,
    MedicationAdherence,
    AdherenceByMedication,
    AdherenceHistoryEntry,
    AdherenceHistory,
    DailySummary,
    WeeklyTrend,
    WeeklyTrendList,
    ProblemTime,
    ProblemTimesResponse,
    AdherenceDashboard,
)

from api.schemas.symptom import (
    SeverityLevelEnum,
    SymptomReportCreate,
    SymptomReportUpdate,
    SymptomResolve,
    SymptomQuery,
    SymptomReportResponse,
    SymptomReportDetail,
    SymptomSummary,
    SymptomCorrelation,
    CorrelationAnalysis,
    PotentialSideEffect,
    SideEffectsAnalysis,
    SymptomTrend,
    SymptomTrendList,
    SevereSymptom,
    SevereSymptomsResponse,
    SymptomProviderReport,
    SymptomList,
)

from api.schemas.report import (
    ReportCreate,
    ReportQuery,
    QuickSummaryRequest,
    AdherenceSummary,
    MedicationSummaryItem,
    SymptomSummaryItem,
    SymptomReportSummary,
    BarrierSummaryItem,
    BarrierReportSummary,
    InterventionItem,
    Recommendation,
    ProviderReportResponse,
    ProviderReportDetail,
    ProviderReportSummary,
    ReportList,
    QuickSummaryResponse,
    FHIRBundle,
    FHIRExportResponse,
    ReportExportResponse,
    ReportAnalytics,
)


__all__ = [
    # Patient schemas
    "PatientBase",
    "PatientCreate",
    "PatientUpdate",
    "PatientPreferencesUpdate",
    "ConditionAdd",
    "AllergyAdd",
    "PatientResponse",
    "PatientSummary",
    "PatientDetailResponse",
    "PatientList",
    "PatientSearch",
    # Medication schemas
    "MedicationBase",
    "MedicationCreate",
    "MedicationUpdate",
    "MedicationDiscontinue",
    "InteractionCheckRequest",
    "MedicationSearch",
    "MedicationResponse",
    "MedicationSummary",
    "MedicationDetail",
    "MedicationList",
    "DrugInteraction",
    "InteractionCheckResponse",
    "DrugSearchResult",
    "SideEffectsResponse",
    "FoodRequirementsResponse",
    "RefillNeeded",
    "RefillList",
    # Adherence schemas
    "AdherenceStatusEnum",
    "AdherenceLogCreate",
    "DoseTaken",
    "DoseMissed",
    "DoseSkipped",
    "AdherenceQuery",
    "AdherenceLogResponse",
    "AdherenceLogDetail",
    "AdherenceRate",
    "AdherenceStreak",
    "MedicationAdherence",
    "AdherenceByMedication",
    "AdherenceHistoryEntry",
    "AdherenceHistory",
    "DailySummary",
    "WeeklyTrend",
    "WeeklyTrendList",
    "ProblemTime",
    "ProblemTimesResponse",
    "AdherenceDashboard",
    # Symptom schemas
    "SeverityLevelEnum",
    "SymptomReportCreate",
    "SymptomReportUpdate",
    "SymptomResolve",
    "SymptomQuery",
    "SymptomReportResponse",
    "SymptomReportDetail",
    "SymptomSummary",
    "SymptomCorrelation",
    "CorrelationAnalysis",
    "PotentialSideEffect",
    "SideEffectsAnalysis",
    "SymptomTrend",
    "SymptomTrendList",
    "SevereSymptom",
    "SevereSymptomsResponse",
    "SymptomProviderReport",
    "SymptomList",
    # Report schemas
    "ReportCreate",
    "ReportQuery",
    "QuickSummaryRequest",
    "AdherenceSummary",
    "MedicationSummaryItem",
    "SymptomSummaryItem",
    "SymptomReportSummary",
    "BarrierSummaryItem",
    "BarrierReportSummary",
    "InterventionItem",
    "Recommendation",
    "ProviderReportResponse",
    "ProviderReportDetail",
    "ProviderReportSummary",
    "ReportList",
    "QuickSummaryResponse",
    "FHIRBundle",
    "FHIRExportResponse",
    "ReportExportResponse",
    "ReportAnalytics",
]
